# Generated by Django 4.0.3 on 2022-07-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=200)),
                ('shortname', models.CharField(max_length=200)),
                ('longname', models.CharField(max_length=200)),
                ('exchange', models.CharField(max_length=200)),
                ('market', models.CharField(max_length=200)),
                ('quoteType', models.CharField(max_length=200)),
            ],
        ),
    ]
