# Generated by Django 4.0.3 on 2022-07-11 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocksymbol',
            old_name='longname',
            new_name='longName',
        ),
        migrations.RenameField(
            model_name='stocksymbol',
            old_name='shortname',
            new_name='shortName',
        ),
    ]
